ALTER TABLE "PriceEvent"
ADD COLUMN "close" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "prevClose" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "changePercent" DOUBLE PRECISION NOT NULL DEFAULT 0;
